### ISSUE TITLE
Feature request: milliseconds.toSeconds

### ISSUE THREAD

**Issue by gavacho** [HenrikJoreteg/milliseconds#4]
This library is great! The only thing I find myself missing is a `milliseconds.toSeconds` function that I could use to:

- Convert a JS timestamp (milliseconds since epoch) into a unix timestamp (seconds since epoch)
- Pass values to third-party-library functions which expect seconds instead of milliseconds.

```js
// example usage
console.log({
  'a unix timestamp': milliseconds.toSeconds(Date.now()),
  'do this in 15 minutes': milliseconds.toSeconds(milliseconds.minutes(15)),
});
```

This function compliments this library nicely but is so small that it doesn't really warrant its own library. What do you think? Is it related enough to "mess with perfection" and add it to this library?

**Comment by HenrikJoreteg** [comment]
Hi @gavacho 👋 very interesting... i don't quite know if this fits. I mean, I find myself needing this at times too. But I don't quite feel like it belongs *in* this lib. It feels like something you could pretty easily do as a util in an app that needs it:

`Math.round(milliseconds / 1000)` is easy enough to do, I think I'm going to pass on the suggestion. Thanks though!!
